language: python
python:
  - 3.2
  - 3.3
  - 3.4

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements.txt
  - pip install coveralls

script:
  coverage run --source=ember_index setup.py test

after_success:
  coveralls
